### ISSUE TITLE
Error after run train_network.py but not always

### ISSUE THREAD

**Issue by globalik** [drscotthawley/panotti#26]
Hi i got error after run train_network.py but not everytimes. 
I trained on my graphics card.
One class is allways 40 npy files.
If used 2 classes (80 npy files)  everythng work correctly,
If used 4 classes (160 npy files) and i got a error (i thing that it's memory problem but i don't know)
This is errorlist: https://pastebin.com/iFTNVEQn

My laptop specification: OS: Windows 10
                                       Graphics card: Nvidia GTX 950m 2GB
                                       RAM: 8GB DDR4

I finally want used 10 classes but at this moment work only 2 classes

Please help me.

**Comment by drscotthawley** [comment]
Hi @globalik. Looks like you're running on a Windows system, which as it says in the README, I have no experience with. 
Also looks like you're getting "out of memory" errors from tensorflow.  Which, given that you've only got 8GB of RAM and only 2GB of VRAM seems entirely appropriate.  This agrees with your ability to run 2 classes but not 4.  
So, my recommendation is that you try running on a non-Windows system with more RAM & VRAM.  Perhaps an AWS g2_2xlarge Ubuntu instance.

One other simple thing you could try would be to decrease the batch size.  There's a command-line parameter "--batch_size"  that defaults to 40.   Try running train_network.py with --batch_size=10.

**Comment by globalik** [comment]
thanks this solution works.
