### ISSUE TITLE
Output

### ISSUE THREAD

**Issue by Wild1234** [drscotthawley/panotti#29]
Good night.

The results of the test set present the accuracy of the different wav files?
I want to create a model that classifies laughing, crying and other emotions.
The results appear on the command line?

Thanks in advance.

**Comment by drscotthawley** [comment]
Sorry, I don't understand the question.  "the accuracy of the different wav files"? It is the accuracy of the classifier's classifications.  I don't know what "appear on the command line" could mean.  A command line is for input.
