### ISSUE TITLE
Problem loading class data in train_network 

### ISSUE THREAD

**Issue by gllort** [drscotthawley/panotti#32]
I'm trying to run a test with ~500 classes and ~80K files, and right at the end of the first step of loading the classes input data, I'm getting the following error:

  File "panotti/panotti/datautils.py", line 235, in build_dataset
    X[load_count,:,:] = melgram
IndexError: index 64837 is out of bounds for axis 0 with size 64837

At the beginning, the output shows that this is the total number of files that are going to be loaded: 

going to load total_load =  64837

I was able to reproduce the problem with a smaller input (~700 files). This is the full output:

Using TensorFlow backend.
class_names =  ['1', '2', '3', '4', '5']
       total files =  780 , going to load total_load =  760
total files =  780 , going to load total_load =  760
   get_sample_dimensions: 1-140000-145000-44100-2-348093.wav.npz: melgram.shape =  (1, 96, 431, 2)
 melgram dimensions:  (1, 96, 431, 2)

 Loading class 1/5: '1', File 275/275: Preproc/Train/1/1-55500-60500-44100-2-348093.wav.npz                    
 Loading class 2/5: '2', File 216/216: Preproc/Train/2/2-105000-110000-44100-2-275506.wav.npz                  
 Loading class 3/5: '3', File 108/108: Preproc/Train/3/3-54000-59000-44100-2-139023.wav.npz                  
 Loading class 4/5: '4', File 101/162: Preproc/Train/4/4-49500-54500-44100-2-166661.wav.npz                  
 Loading class 5/5: '5', File 1/19: Preproc/Train/5/5-10000-15000-44100-2-28040.wav.npz                  Traceback (most recent call last):
  File "train_network.py", line 63, in <module>
    val_split=args.val, tile=args.tile)
  File "train_network.py", line 29, in train_network
    X_train, Y_train, paths_train, class_names = build_dataset(path=classpath, batch_size=batch_size, tile=tile)
  File "panotti/panotti/datautils.py", line 235, in build_dataset
    X[load_count,:,:] = melgram
IndexError: index 760 is out of bounds for axis 0 with size 760

Looking into panotti/datautils.py line 235, it seems that the problem is that the load_count counter reaches the value of total_load before processing the last class, so the break statement in line 240 stops the inner loop (that iterates files in a class), but not the outer loop (that iterates through classes), so it still tries to process the next class' files, and it crashes when indexing the array X out of scope because load_count is already over the limit.

**Comment by drscotthawley** [comment]
@gllort Thanks for the feedback. Let me go in and fix that...

**Comment by drscotthawley** [comment]
@gllort Changes made in dev branch, updated to master in https://github.com/drscotthawley/panotti/pull/33   .  Thanks!
