### ISSUE TITLE
Filters coefficients

### ISSUE THREAD

**Issue by gdf47** [drscotthawley/panotti#42]
I want to ask you: What kind filters can we use for Conv2D? I see only 3*3 (That's the dimension) but I don't know what this Matrix has as parameters or coeffecients. Or when I just give that function Conv2D with numbers of filters and the filter's dimension, does it choose random coeffecients for this Matrix?  What I did right noyw: Generate spectograms and save them as data (Matrix), but I'm confuses about this filters and the only thing that I cannot understand.  Can you give me some informations about it?

**Comment by gdf47** [comment]
Thank you very much for your explanation and your fast reply @drscotthawley. Now I get it how it works. 
Another question: Should I fix the dimensions of  my data in order to know how many layers will I use for convolution to get a vector as an Input for NN? I see that you fixed the shape of inputs and concatenate with zero when they are smaller right?

**Comment by gdf47** [comment]
Thank your @drscotthawley  for your fast reply. That helps a lot. 
Can I come back to ask you again when I don't understand soemthing with CNN ?

**Comment by gdf47** [comment]
Thank you  @drscotthawley for your help last time. 
 I converted every .wav file to an array of 2 dimensions (.npy). And now I want to give this data to CNN (using Keras). The problem here I have a problem with the input.
- Is there like a fixed shape for inputs (4D?) I saw that you always use (np.newaxis) to add 2 dimensions one for number of samples and the other one is just number of channels (you put 3 but isn't it 1 because we will use just mono?) Here when I save the data as 3D (number of samples, mels, data.shape[2]) to make it easier to load it in My CNN, The data size increases from 900 Kb to 160 Mb (Do you think that's a bad idea?). 
- must the inputs have the same shape? (for example I have to fix array’s shape to 128(mel)*700 of all my inputs, even though they don't have the same duration? I fixed Max as 700 and added rows of zeros if the X.shape[1] less than 700? is that what you did?

**Comment by drscotthawley** [comment]
Hi @gdf47. It's not really my place to answer general questions about CNN. For that, please use StackExchange.  

I don't have problems using a variety of audio files.  I'm not sure what files you're using, but the questions indicate that you're not using the full code, which definitely does make all the spectrograms the same shape.  

I'm going to close this out because I don't think you're describing an issue with this code.
