### ISSUE TITLE
Modifying original data in augment_audio.py

### ISSUE THREAD

**Issue by FelixAbrahamsson** [drscotthawley/panotti#46]
You might want to change line 34 from `y_mod = y` to `y_mod = y.copy()` or something similar, otherwise some of the operations end up modifying the original data.

Very useful script by the way, thank you!

**Comment by drscotthawley** [comment]
Thanks @FelixAbrahamsson!  Missed that.  Will make a quick change and push it to main...

**Comment by drscotthawley** [comment]
Change made.  Closing.
