### ISSUE TITLE
Error after run preprocess_data.py

### ISSUE THREAD

**Issue by globalik** [drscotthawley/panotti#5]
Hi I try run this neural network but  after the first step i run script preprocess_data.py i get error: ValueError: not enough values to unpack (expected 13, got 0)

I tried too previous version: https://github.com/drscotthawley/audio-classifier-keras-cnn and this code work correctly

I use this previous version it on OS: WIndows 10 and trained neural network on my graphics card GTX950m 

I can use previously version but don't know how i can change number of layers and other parameters this neural network so that work it. 

Here is image my error: https://imgur.com/a/NdjFV

Sorry for my bad english and thanks for reply.

**Comment by drscotthawley** [comment]
Interesting.  I have no experience running on Windows 10, as my machine is Ubuntu 16.04.  But if you would like to share a sample part of your dataset that reproduces the error (e.g. via DropBox or another cloud-drive service), I can try it on my end and see if I run into the same problem.

**Comment by globalik** [comment]
Hi thanks for your reply. I using  this dataset: https://github.com/karoldvl/ESC-50
I choose two class from this dataset who are here: https://drive.google.com/open?id=1HOTXMnGOMqTkqLrwSnZp8acgEAqGJiqb

When i used this two class for older version your code: https://github.com/drscotthawley/audio-classifier-keras-cnn everything work correctly. Here is screenshot: https://imgur.com/a/N1Frv

Please help me. Thanks for reply

**Comment by globalik** [comment]
Hello, have you found a solution for this error?

**Comment by drscotthawley** [comment]
@globalik Thanks for the reminder.  Sorry, I have been busy with other things. I'll take a look over the weekend.

**Comment by drscotthawley** [comment]
@globalik Try it with the latest version of preprocess_data.py  I just tried your dataset with that and received no errors.

**Comment by globalik** [comment]
Thanks now preprocess_data works. You are genius thanks very much.
