### ISSUE TITLE
AttributeError: 'module' object has no attribute 'cpu_count'   when running preprocess_data.py

### ISSUE THREAD

**Issue by manbharae** [drscotthawley/panotti#6]
Thank you for the nice project Professor. 
I am getting the following error when running the preprocess_data.py
Traceback (most recent call last):
  File "preprocess_data.py", line 152, in <module>
    preprocess_dataset(resample=44100, already_split=args.already, sequential=args.sequential, mono=args.mono)
  File "preprocess_data.py", line 109, in preprocess_dataset
    pool = Pool(os.cpu_count())
AttributeError: 'module' object has no attribute 'cpu_count'

I google and found : https://github.com/tensorflow/tensorflow/issues/6513
but no change even after trying :    

pip install --user --upgrade psutil
Collecting psutil
Installing collected packages: psutil
Successfully installed psutil-5.4.3

**Comment by drscotthawley** [comment]
Upgrading psutil wouldn't affect the os package, because we're using os.cpu_count() not psutil.cpu_count().    os.cpu_count() is a standard part of os in Python 3.5 on (https://docs.python.org/3/library/os.html).   Tell me more about your Python installation.

**Comment by manbharae** [comment]
Professor, thank you for the quick reply. 
I have both python 2.7 and python 3.5.2

```
man@man:~$ python
Python 2.7.12 (default, Nov 20 2017, 18:23:56) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
man@man:~$ python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01) 
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

is there any thing else that I can post so that it will provide more information?

**Comment by manbharae** [comment]
I think this line is causing error : `os.cpu_count()` 
According to this : https://docs.python.org/2.7/library/os.html#module-os and https://docs.python.org/3.5/library/os.html#module-os  

`os` has no `.cpu_count()` function

**Comment by drscotthawley** [comment]
On Jan 23, 2018, at 9:33 PM, Manio Bharae <notifications@github.com<mailto:notifications@github.com>> wrote:


I think this line is causing error : os.cpu_count()
According to this : https://docs.python.org/2.7/library/os.html#module-os and https://docs.python.org/3.5/library/os.html#module-os

os has no .cpu_count() function

Yes it does.  The second link you provided absolutely has it.  Try searching on that exact web page.

Panotti is a Python 3.5 application.  Trying to run it with Python 2.7 will generate all manner of errors, including errors at print statements.

**Comment by drscotthawley** [comment]
@manbharae  My apologies.  Panotti was once compatible with Python 2.7, but I eventually switched to Python 3.5 a while ago and failed to update the README.md file accordingly.  I'm sorry for the frustration this may have caused.

**Comment by manbharae** [comment]
@drscotthawley  that is not at all a problem Professor. There is No cause for concern nor any frustration! It is all Good. :-) 
It was about time I migrated to Python 3.5 :-) 
Once again thank you for all the effort in making such a nice project available to us!
