### ISSUE TITLE
[New Feature Request] tracking where in an audio a given sound exists

### ISSUE THREAD

**Issue by StanSilas** [drscotthawley/panotti#7]
Dear Professor,
Thanks for making this amazing project available!.

I was wondering if/how this project may be extended beyond its current offering to "track a particular class of sound in a test audio".      

Say we have 5 folders with 5 types of sounds and the model is trained on them. 
then when a new audio(say of duration 3 minutes) is given as the test input. 
`_I would like to track where in that audio file a particular class of sound occurs._
`
**Example :** 
sounds are : rings , clicks , drums, guitar and whistling.
Test audio is a 3 minute long .mp3 made of  non overlapping ^ sounds. 

If I'd like to track the class  `whistling` , the model should tell me where in the test audio is the whistling present, if at all present. 

Thank you.

**Comment by kasbah** [comment]
What you are describing is a signal processing problem and may be out of scope for this project. A model trained with Panotti could be used this way but it would probably be best to develop it as a separate bit of code.

The way I would approach it is to use a window the length of your training examples and pass that over your input audio. So if your training examples are 10 seconds then you first run your network on 0:00 to 0:10 then on 0:01 to 0:11 then 0:02 to 0:12 etc. Using a one second granularity is probably too coarse, but you get the idea. [Windowing](https://en.wikipedia.org/wiki/Window_function) can get pretty complicated in itself too as you can use all sorts of different functions/shapes.

Doing this in real-time, i.e. as the audio comes in would be an extra challenge.

**Comment by drscotthawley** [comment]
@StanSilas @kasbah I was thinking about this last night in fact.  The "segmentation" problem you are describing could be solved by an "object detection" algorithm such as [YOLO](https://pjreddie.com/darknet/yolo/) or Fast-RCNN.  I've actually written a YOLO-like object detection code for images but have not applied to audio yet.  It could be adapted and 'swapped into' panotti but I don't foresee having time to do this in the near future.

**Comment by drscotthawley** [comment]
I'm going to close is as beyond the scope of the current code.  Like I say, it could be done by splitting up the loss function into the sum of classification (which sound) & regression (when it occurs) parts.
